// ============================================================
// Code export: assembles a standalone single-file server.js for a
// bot, from fixed templates + the flow serialized as JSON.
// Purely deterministic string assembly — no AI.
// ============================================================

function generateTwilio(flow) {
  const creds = flow.twilio || {};
  const flowJson = JSON.stringify(
    { nodes: flow.nodes.map(({ id, type, config }) => ({ id, type, config })), edges: flow.edges },
    null,
    2
  );

  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot server
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook: POST http://<your-host>:3000/whatsapp  (set in Twilio Sandbox)
// ============================================================

const express = require("express");

const TWILIO = {
  accountSid: process.env.TWILIO_SID || "${creds.sid || "YOUR_TWILIO_ACCOUNT_SID"}",
  authToken:  process.env.TWILIO_TOKEN || "${creds.token ? "SET_VIA_ENV_VAR" : "YOUR_TWILIO_AUTH_TOKEN"}",
  whatsappNumber: "${creds.number || "whatsapp:+14155238886"}",
};

// ---- Your flowchart, serialized ----
const FLOW = ${flowJson};

// ---- Pre-embedded engine (one handler per feature block) ----
const interp = (m, v) => m.replace(/\\{(\\w+)\\}/g, (_, k) => v[k] ?? k);
const byId = Object.fromEntries(FLOW.nodes.map(n => [n.id, n]));
const next = (id, port) => {
  const e = FLOW.edges.find(x => x.from === id && x.fromPort === port);
  return e ? byId[e.to] : null;
};
const sessions = {}; // per-phone: { state, vars }

function handleMessage(text, s) {
  const out = [];
  function runFrom(node) {
    let cur = node, guard = 0;
    while (cur && guard++ < 50) {
      const c = cur.config;
      switch (cur.type) {
        case "welcome": out.push(c.message); cur = next(cur.id, 0); break;
        case "menu":
          out.push(c.prompt + "\\n\\n" + c.options.map((o,i) => (i+1) + ". " + o).join("\\n") + "\\n\\nReply with a number.");
          s.state = cur.id; return;
        case "faq":
          out.push("Ask me anything — keywords: " + c.pairs.map(p => p.k).join(", ") + ". Type 0 when done.");
          s.state = cur.id; return;
        case "collect": out.push(c.question); s.state = cur.id; return;
        case "goodbye": out.push(interp(c.message, s.vars)); s.state = null; s.vars = {}; return;
        default: cur = next(cur.id, 0);
      }
    }
    if (!cur) s.state = null;
  }

  const t = String(text || "").trim();
  if (!s.state) {
    const start = FLOW.nodes.find(n => n.type === "welcome");
    if (!start) { out.push("This bot has no Welcome block."); return out; }
    runFrom(start); return out;
  }
  const cur = byId[s.state];
  if (!cur) { s.state = null; return handleMessage(text, s); }

  if (cur.type === "menu") {
    const i = parseInt(t, 10) - 1;
    if (Number.isInteger(i) && i >= 0 && i < cur.config.options.length) {
      const nx = next(cur.id, i);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
    } else out.push("Please reply with a number between 1 and " + cur.config.options.length + ".");
    return out;
  }
  if (cur.type === "faq") {
    if (t === "0") {
      const nx = next(cur.id, 0);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
      return out;
    }
    const hit = cur.config.pairs.find(p => t.toLowerCase().includes(p.k.toLowerCase()));
    out.push(hit ? hit.a : "No answer for that yet. Try another keyword or type 0.");
    return out;
  }
  if (cur.type === "collect") {
    s.vars[cur.config.field] = t;
    out.push("Got it.");
    const nx = next(cur.id, 0);
    if (nx) runFrom(nx); else s.state = null;
    return out;
  }
  s.state = null;
  return out;
}

// ---- TwiML helpers (hand-rolled, so the only dependency is express) ----
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const twiml = (msgs) =>
  '<?xml version="1.0" encoding="UTF-8"?><Response>' +
  msgs.map(m => "<Message>" + esc(m) + "</Message>").join("") +
  "</Response>";

// ---- Server ----
const app = express();
app.use(express.urlencoded({ extended: false }));

app.post("/whatsapp", (req, res) => {
  const from = req.body.From || "unknown";
  const body = req.body.Body || "";
  const s = sessions[from] || (sessions[from] = { state: null, vars: {} });
  res.type("text/xml").send(twiml(handleMessage(body, s)));
});

app.get("/", (_req, res) => res.send("${(flow.name || "FlowBot").replace(/"/g, "")} is running. Webhook: POST /whatsapp"));

app.listen(3000, () => console.log("Bot listening on :3000 — webhook: POST /whatsapp"));
`;
}

function generateMeta(flow) {
  const meta = flow.meta || {};
  const flowJson = JSON.stringify(
    { nodes: flow.nodes.map(({ id, type, config }) => ({ id, type, config })), edges: flow.edges },
    null,
    2
  );

  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot (Meta Cloud API)
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook (set in Meta App → WhatsApp → Configuration):
//   Callback URL:  https://<your-host>:3000/webhook
//   Verify token:  see META.verifyToken below
// ============================================================

const express = require("express");

const META = {
  accessToken:   process.env.META_ACCESS_TOKEN || "${meta.accessToken ? "SET_VIA_ENV_VAR" : "YOUR_META_ACCESS_TOKEN"}",
  phoneNumberId: process.env.META_PHONE_NUMBER_ID || "${meta.phoneNumberId || "YOUR_PHONE_NUMBER_ID"}",
  verifyToken:   process.env.META_VERIFY_TOKEN || "${meta.verifyToken || "flowbot-verify"}",
  graphBase:     "https://graph.facebook.com/v21.0",
};

// ---- Your flowchart, serialized ----
const FLOW = ${flowJson};

// ---- Pre-embedded engine (one handler per feature block) ----
const interp = (m, v) => m.replace(/\\{(\\w+)\\}/g, (_, k) => v[k] ?? k);
const byId = Object.fromEntries(FLOW.nodes.map(n => [n.id, n]));
const next = (id, port) => {
  const e = FLOW.edges.find(x => x.from === id && x.fromPort === port);
  return e ? byId[e.to] : null;
};
const sessions = {}; // per-phone: { state, vars }

function handleMessage(text, s) {
  const out = [];
  function runFrom(node) {
    let cur = node, guard = 0;
    while (cur && guard++ < 50) {
      const c = cur.config;
      switch (cur.type) {
        case "welcome": out.push(c.message); cur = next(cur.id, 0); break;
        case "menu":
          out.push(c.prompt + "\\n\\n" + c.options.map((o,i) => (i+1) + ". " + o).join("\\n") + "\\n\\nReply with a number.");
          s.state = cur.id; return;
        case "faq":
          out.push("Ask me anything — keywords: " + c.pairs.map(p => p.k).join(", ") + ". Type 0 when done.");
          s.state = cur.id; return;
        case "collect": out.push(c.question); s.state = cur.id; return;
        case "goodbye": out.push(interp(c.message, s.vars)); s.state = null; s.vars = {}; return;
        default: cur = next(cur.id, 0);
      }
    }
    if (!cur) s.state = null;
  }

  const t = String(text || "").trim();
  if (!s.state) {
    const start = FLOW.nodes.find(n => n.type === "welcome");
    if (!start) { out.push("This bot has no Welcome block."); return out; }
    runFrom(start); return out;
  }
  const cur = byId[s.state];
  if (!cur) { s.state = null; return handleMessage(text, s); }

  if (cur.type === "menu") {
    const i = parseInt(t, 10) - 1;
    if (Number.isInteger(i) && i >= 0 && i < cur.config.options.length) {
      const nx = next(cur.id, i);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
    } else out.push("Please reply with a number between 1 and " + cur.config.options.length + ".");
    return out;
  }
  if (cur.type === "faq") {
    if (t === "0") {
      const nx = next(cur.id, 0);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
      return out;
    }
    const hit = cur.config.pairs.find(p => t.toLowerCase().includes(p.k.toLowerCase()));
    out.push(hit ? hit.a : "No answer for that yet. Try another keyword or type 0.");
    return out;
  }
  if (cur.type === "collect") {
    s.vars[cur.config.field] = t;
    out.push("Got it.");
    const nx = next(cur.id, 0);
    if (nx) runFrom(nx); else s.state = null;
    return out;
  }
  s.state = null;
  return out;
}

// ---- Graph API sender ----
async function sendText(to, body) {
  const res = await fetch(META.graphBase + "/" + META.phoneNumberId + "/messages", {
    method: "POST",
    headers: { Authorization: "Bearer " + META.accessToken, "Content-Type": "application/json" },
    body: JSON.stringify({ messaging_product: "whatsapp", to, type: "text", text: { body } }),
  });
  if (!res.ok) console.error("Graph API error", res.status, await res.text().catch(() => ""));
}

// ---- Server ----
const app = express();
app.use(express.json());

// Webhook verification handshake
app.get("/webhook", (req, res) => {
  if (req.query["hub.mode"] === "subscribe" && req.query["hub.verify_token"] === META.verifyToken) {
    return res.status(200).send(req.query["hub.challenge"]);
  }
  res.sendStatus(403);
});

// Incoming messages
app.post("/webhook", async (req, res) => {
  const msg = req.body?.entry?.[0]?.changes?.[0]?.value?.messages?.[0];
  if (msg) {
    const from = msg.from;
    const text = msg.text?.body ?? msg.interactive?.button_reply?.title ?? msg.button?.text ?? "";
    const s = sessions[from] || (sessions[from] = { state: null, vars: {} });
    for (const reply of handleMessage(text, s)) await sendText(from, reply);
  }
  res.sendStatus(200);
});

app.get("/", (_req, res) => res.send("${(flow.name || "FlowBot").replace(/"/g, "")} is running (Meta Cloud API). Webhook: /webhook"));

app.listen(3000, () => console.log("Bot listening on :3000 — webhook: /webhook"));
`;
}

function generateGreen(flow) {
  const green = flow.green || {};
  const flowJson = JSON.stringify(
    { nodes: flow.nodes.map(({ id, type, config }) => ({ id, type, config })), edges: flow.edges },
    null,
    2
  );

  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot (Green API)
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook (set in Green API console):
//   Webhook URL:  https://<your-host>:3000/webhook
// ============================================================

const express = require("express");

const GREEN = {
  idInstance:      process.env.GREEN_ID_INSTANCE || "${green.idInstance || "YOUR_ID_INSTANCE"}",
  apiTokenInstance: process.env.GREEN_API_TOKEN_INSTANCE || "${green.apiTokenInstance ? "SET_VIA_ENV_VAR" : "YOUR_API_TOKEN_INSTANCE"}",
  apiUrl:          (process.env.GREEN_API_URL || "${green.apiUrl || "https://api.green-api.com"}").replace(/\\/+$/, ""),
};

// ---- Your flowchart, serialized ----
const FLOW = ${flowJson};

// ---- Pre-embedded engine (one handler per feature block) ----
const interp = (m, v) => m.replace(/\\{(\\w+)\\}/g, (_, k) => v[k] ?? k);
const byId = Object.fromEntries(FLOW.nodes.map(n => [n.id, n]));
const next = (id, port) => {
  const e = FLOW.edges.find(x => x.from === id && x.fromPort === port);
  return e ? byId[e.to] : null;
};
const sessions = {}; // per-chat: { state, vars }

function handleMessage(text, s) {
  const out = [];
  function runFrom(node) {
    let cur = node, guard = 0;
    while (cur && guard++ < 50) {
      const c = cur.config;
      switch (cur.type) {
        case "welcome": out.push(c.message); cur = next(cur.id, 0); break;
        case "menu":
          out.push(c.prompt + "\\n\\n" + c.options.map((o,i) => (i+1) + ". " + o).join("\\n") + "\\n\\nReply with a number.");
          s.state = cur.id; return;
        case "faq":
          out.push("Ask me anything — keywords: " + c.pairs.map(p => p.k).join(", ") + ". Type 0 when done.");
          s.state = cur.id; return;
        case "collect": out.push(c.question); s.state = cur.id; return;
        case "goodbye": out.push(interp(c.message, s.vars)); s.state = null; s.vars = {}; return;
        default: cur = next(cur.id, 0);
      }
    }
    if (!cur) s.state = null;
  }

  const t = String(text || "").trim();
  if (!s.state) {
    const start = FLOW.nodes.find(n => n.type === "welcome");
    if (!start) { out.push("This bot has no Welcome block."); return out; }
    runFrom(start); return out;
  }
  const cur = byId[s.state];
  if (!cur) { s.state = null; return handleMessage(text, s); }

  if (cur.type === "menu") {
    const i = parseInt(t, 10) - 1;
    if (Number.isInteger(i) && i >= 0 && i < cur.config.options.length) {
      const nx = next(cur.id, i);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
    } else out.push("Please reply with a number between 1 and " + cur.config.options.length + ".");
    return out;
  }
  if (cur.type === "faq") {
    if (t === "0") {
      const nx = next(cur.id, 0);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
      return out;
    }
    const hit = cur.config.pairs.find(p => t.toLowerCase().includes(p.k.toLowerCase()));
    out.push(hit ? hit.a : "No answer for that yet. Try another keyword or type 0.");
    return out;
  }
  if (cur.type === "collect") {
    s.vars[cur.config.field] = t;
    out.push("Got it.");
    const nx = next(cur.id, 0);
    if (nx) runFrom(nx); else s.state = null;
    return out;
  }
  s.state = null;
  return out;
}

// ---- Green API helpers ----
function extractIncoming(body) {
  if (body?.typeWebhook !== "incomingMessageReceived") return null;
  const messageData = body.messageData || {};
  const text =
    messageData.textMessageData?.textMessage ??
    messageData.extendedTextMessageData?.text ??
    messageData.quotedMessage?.textMessage ??
    "";
  const from = body.senderData?.chatId || body.senderData?.sender || "";
  return from ? { from, text } : null;
}

async function sendText(chatId, message) {
  const url = GREEN.apiUrl + "/waInstance" + GREEN.idInstance + "/sendMessage/" + GREEN.apiTokenInstance;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chatId, message }),
  });
  if (!res.ok) console.error("Green API error", res.status, await res.text().catch(() => ""));
}

// ---- Server ----
const app = express();
app.use(express.json());

app.post("/webhook", async (req, res) => {
  const incoming = extractIncoming(req.body);
  if (incoming) {
    const s = sessions[incoming.from] || (sessions[incoming.from] = { state: null, vars: {} });
    for (const reply of handleMessage(incoming.text, s)) await sendText(incoming.from, reply);
  }
  res.sendStatus(200);
});

app.get("/", (_req, res) => res.send("${(flow.name || "FlowBot").replace(/"/g, "")} is running (Green API). Webhook: /webhook"));

app.listen(3000, () => console.log("Bot listening on :3000 — webhook: /webhook"));
`;
}

function generateWhapi(flow) {
  const whapi = flow.whapi || {};
  const flowJson = JSON.stringify(
    { nodes: flow.nodes.map(({ id, type, config }) => ({ id, type, config })), edges: flow.edges },
    null,
    2
  );

  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot (Whapi.cloud)
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook (set in Whapi.cloud channel settings):
//   Webhook URL:  https://<your-host>:3000/webhook
// ============================================================

const express = require("express");

const WHAPI = {
  token:  process.env.WHAPI_TOKEN || "${whapi.token ? "SET_VIA_ENV_VAR" : "YOUR_WHAPI_TOKEN"}",
  apiUrl: (process.env.WHAPI_API_URL || "${whapi.apiUrl || "https://gate.whapi.cloud"}").replace(/\\/+$/, ""),
};

// ---- Your flowchart, serialized ----
const FLOW = ${flowJson};

// ---- Pre-embedded engine (one handler per feature block) ----
const interp = (m, v) => m.replace(/\\{(\\w+)\\}/g, (_, k) => v[k] ?? k);
const byId = Object.fromEntries(FLOW.nodes.map(n => [n.id, n]));
const next = (id, port) => {
  const e = FLOW.edges.find(x => x.from === id && x.fromPort === port);
  return e ? byId[e.to] : null;
};
const sessions = {}; // per-chat: { state, vars }

function handleMessage(text, s) {
  const out = [];
  function runFrom(node) {
    let cur = node, guard = 0;
    while (cur && guard++ < 50) {
      const c = cur.config;
      switch (cur.type) {
        case "welcome": out.push(c.message); cur = next(cur.id, 0); break;
        case "menu":
          out.push(c.prompt + "\\n\\n" + c.options.map((o,i) => (i+1) + ". " + o).join("\\n") + "\\n\\nReply with a number.");
          s.state = cur.id; return;
        case "faq":
          out.push("Ask me anything — keywords: " + c.pairs.map(p => p.k).join(", ") + ". Type 0 when done.");
          s.state = cur.id; return;
        case "collect": out.push(c.question); s.state = cur.id; return;
        case "goodbye": out.push(interp(c.message, s.vars)); s.state = null; s.vars = {}; return;
        default: cur = next(cur.id, 0);
      }
    }
    if (!cur) s.state = null;
  }

  const t = String(text || "").trim();
  if (!s.state) {
    const start = FLOW.nodes.find(n => n.type === "welcome");
    if (!start) { out.push("This bot has no Welcome block."); return out; }
    runFrom(start); return out;
  }
  const cur = byId[s.state];
  if (!cur) { s.state = null; return handleMessage(text, s); }

  if (cur.type === "menu") {
    const i = parseInt(t, 10) - 1;
    if (Number.isInteger(i) && i >= 0 && i < cur.config.options.length) {
      const nx = next(cur.id, i);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
    } else out.push("Please reply with a number between 1 and " + cur.config.options.length + ".");
    return out;
  }
  if (cur.type === "faq") {
    if (t === "0") {
      const nx = next(cur.id, 0);
      if (nx) runFrom(nx); else { s.state = null; out.push("Done! Say hi to start again."); }
      return out;
    }
    const hit = cur.config.pairs.find(p => t.toLowerCase().includes(p.k.toLowerCase()));
    out.push(hit ? hit.a : "No answer for that yet. Try another keyword or type 0.");
    return out;
  }
  if (cur.type === "collect") {
    s.vars[cur.config.field] = t;
    out.push("Got it.");
    const nx = next(cur.id, 0);
    if (nx) runFrom(nx); else s.state = null;
    return out;
  }
  s.state = null;
  return out;
}

// ---- Whapi.cloud helpers ----
function extractText(msg) {
  return (
    msg?.text?.body ??
    msg?.link_preview?.body ??
    msg?.reply?.buttons_reply?.title ??
    msg?.reply?.list_reply?.title ??
    msg?.document?.caption ??
    msg?.image?.caption ??
    msg?.video?.caption ??
    ""
  );
}

function extractIncoming(body) {
  const msg = (body?.messages || []).find((m) => !m.from_me);
  if (!msg) return null;
  const from = msg.chat_id || msg.from || "";
  return from ? { from, text: extractText(msg) } : null;
}

async function sendText(to, body) {
  const res = await fetch(WHAPI.apiUrl + "/messages/text", {
    method: "POST",
    headers: { Authorization: "Bearer " + WHAPI.token, "Content-Type": "application/json" },
    body: JSON.stringify({ to, body }),
  });
  if (!res.ok) console.error("Whapi error", res.status, await res.text().catch(() => ""));
}

// ---- Server ----
const app = express();
app.use(express.json());

app.post("/webhook", async (req, res) => {
  const incoming = extractIncoming(req.body);
  if (incoming) {
    const s = sessions[incoming.from] || (sessions[incoming.from] = { state: null, vars: {} });
    for (const reply of handleMessage(incoming.text, s)) await sendText(incoming.from, reply);
  }
  res.sendStatus(200);
});

app.get("/", (_req, res) => res.send("${(flow.name || "FlowBot").replace(/"/g, "")} is running (Whapi.cloud). Webhook: /webhook"));

app.listen(3000, () => console.log("Bot listening on :3000 — webhook: /webhook"));
`;
}

function generateStandalone(flow) {
  if (flow.provider === "meta") return generateMeta(flow);
  if (flow.provider === "green") return generateGreen(flow);
  if (flow.provider === "whapi") return generateWhapi(flow);
  return generateTwilio(flow);
}

module.exports = { generateStandalone };
