// ============================================================
// Code export: assembles a standalone single-file server.js for a
// bot, from fixed templates + the flow serialized as JSON.
// Purely deterministic string assembly — no AI.
// ============================================================

const fs = require("fs");
const path = require("path");

function flowJson(flow) {
  return JSON.stringify(
    { nodes: flow.nodes.map(({ id, type, config }) => ({ id, type, config })), edges: flow.edges },
    null,
    2
  );
}

function embeddedEngine() {
  return fs.readFileSync(path.join(__dirname, "engine.js"), "utf8");
}

function title(flow, suffix = "") {
  return `${(flow.name || "FlowBot").replace(/"/g, "")}${suffix}`;
}

function generateTwilio(flow) {
  const creds = flow.twilio || {};
  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot server
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook: POST http://<your-host>:3000/whatsapp  (set in Twilio Sandbox)
// ============================================================

const express = require("express");

const TWILIO = {
  accountSid: process.env.TWILIO_SID || "${creds.sid || "YOUR_TWILIO_ACCOUNT_SID"}",
  authToken:  process.env.TWILIO_TOKEN || "${creds.token ? "SET_VIA_ENV_VAR" : "YOUR_TWILIO_AUTH_TOKEN"}",
  whatsappNumber: "${creds.number || "whatsapp:+14155238886"}",
};

const FLOW = ${flowJson(flow)};

${embeddedEngine()}

const sessions = {};
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const twiml = (msgs) =>
  '<?xml version="1.0" encoding="UTF-8"?><Response>' +
  msgs.map(m => "<Message>" + esc(m) + "</Message>").join("") +
  "</Response>";

const app = express();
app.use(express.urlencoded({ extended: false }));

app.post("/whatsapp", async (req, res) => {
  const from = req.body.From || "unknown";
  const body = req.body.Body || "";
  const s = sessions[from] || (sessions[from] = { state: null, vars: {} });
  res.type("text/xml").send(twiml(await handleMessage(FLOW, body, s)));
});

app.get("/", (_req, res) => res.send("${title(flow)} is running. Webhook: POST /whatsapp"));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Bot listening on :" + PORT + " — webhook: POST /whatsapp"));
`;
}

function generateMeta(flow) {
  const meta = flow.meta || {};
  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot (Meta Cloud API)
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook: https://<your-host>:3000/webhook
// ============================================================

const express = require("express");

const META = {
  accessToken:   process.env.META_ACCESS_TOKEN || "${meta.accessToken ? "SET_VIA_ENV_VAR" : "YOUR_META_ACCESS_TOKEN"}",
  phoneNumberId: process.env.META_PHONE_NUMBER_ID || "${meta.phoneNumberId || "YOUR_PHONE_NUMBER_ID"}",
  verifyToken:   process.env.META_VERIFY_TOKEN || "${meta.verifyToken || "flowbot-verify"}",
  graphBase:     process.env.GRAPH_API_BASE || "https://graph.facebook.com/v23.0",
};

const FLOW = ${flowJson(flow)};

${embeddedEngine()}

const sessions = {};

async function sendText(to, body) {
  const res = await fetch(META.graphBase + "/" + META.phoneNumberId + "/messages", {
    method: "POST",
    headers: { Authorization: "Bearer " + META.accessToken, "Content-Type": "application/json" },
    body: JSON.stringify({ messaging_product: "whatsapp", to, type: "text", text: { body } }),
  });
  if (!res.ok) console.error("Graph API error", res.status, await res.text().catch(() => ""));
}

const app = express();
app.use(express.json());

app.get("/webhook", (req, res) => {
  if (req.query["hub.mode"] === "subscribe" && req.query["hub.verify_token"] === META.verifyToken) {
    return res.status(200).send(req.query["hub.challenge"]);
  }
  res.sendStatus(403);
});

app.post("/webhook", async (req, res) => {
  const msg = req.body?.entry?.[0]?.changes?.[0]?.value?.messages?.[0];
  if (msg) {
    const from = msg.from;
    const text = msg.text?.body ?? msg.interactive?.button_reply?.title ?? msg.interactive?.list_reply?.title ?? msg.button?.text ?? "";
    const s = sessions[from] || (sessions[from] = { state: null, vars: {} });
    for (const reply of await handleMessage(FLOW, text, s)) await sendText(from, reply);
  }
  res.sendStatus(200);
});

app.get("/", (_req, res) => res.send("${title(flow, " (Meta Cloud API)")} is running. Webhook: /webhook"));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Bot listening on :" + PORT + " — webhook: /webhook"));
`;
}

function generateGreen(flow) {
  const green = flow.green || {};
  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot (Green API)
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook: https://<your-host>:3000/webhook
// ============================================================

const express = require("express");

const GREEN = {
  idInstance:      process.env.GREEN_ID_INSTANCE || "${green.idInstance || "YOUR_ID_INSTANCE"}",
  apiTokenInstance: process.env.GREEN_API_TOKEN_INSTANCE || "${green.apiTokenInstance ? "SET_VIA_ENV_VAR" : "YOUR_API_TOKEN_INSTANCE"}",
  apiUrl:          (process.env.GREEN_API_URL || "${green.apiUrl || "https://api.green-api.com"}").replace(/\\/+$/, ""),
};

const FLOW = ${flowJson(flow)};

${embeddedEngine()}

const sessions = {};

function extractIncoming(body) {
  if (body?.typeWebhook !== "incomingMessageReceived") return null;
  const messageData = body.messageData || {};
  const text =
    messageData.textMessageData?.textMessage ??
    messageData.extendedTextMessageData?.text ??
    messageData.quotedMessage?.textMessage ??
    "";
  const from = body.senderData?.chatId || body.senderData?.sender || "";
  return from ? { from, text } : null;
}

async function sendText(chatId, message) {
  const url = GREEN.apiUrl + "/waInstance" + GREEN.idInstance + "/sendMessage/" + GREEN.apiTokenInstance;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chatId, message }),
  });
  if (!res.ok) console.error("Green API error", res.status, await res.text().catch(() => ""));
}

const app = express();
app.use(express.json());

app.post("/webhook", async (req, res) => {
  const incoming = extractIncoming(req.body);
  if (incoming) {
    const s = sessions[incoming.from] || (sessions[incoming.from] = { state: null, vars: {} });
    for (const reply of await handleMessage(FLOW, incoming.text, s)) await sendText(incoming.from, reply);
  }
  res.sendStatus(200);
});

app.get("/", (_req, res) => res.send("${title(flow, " (Green API)")} is running. Webhook: /webhook"));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Bot listening on :" + PORT + " — webhook: /webhook"));
`;
}

function generateWhapi(flow) {
  const whapi = flow.whapi || {};
  return `// ============================================================
// ${flow.name || "FlowBot"} — standalone WhatsApp bot (Whapi.cloud)
// Generated by FlowBot from your flowchart (template-assembled, no AI).
// Setup:  npm install express   →   node server.js
// Webhook: https://<your-host>:3000/webhook
// ============================================================

const express = require("express");

const WHAPI = {
  token:  process.env.WHAPI_TOKEN || "${whapi.token ? "SET_VIA_ENV_VAR" : "YOUR_WHAPI_TOKEN"}",
  apiUrl: (process.env.WHAPI_API_URL || "${whapi.apiUrl || "https://gate.whapi.cloud"}").replace(/\\/+$/, ""),
};

const FLOW = ${flowJson(flow)};

${embeddedEngine()}

const sessions = {};

function extractText(msg) {
  return (
    msg?.text?.body ??
    msg?.link_preview?.body ??
    msg?.reply?.buttons_reply?.title ??
    msg?.reply?.list_reply?.title ??
    msg?.document?.caption ??
    msg?.image?.caption ??
    msg?.video?.caption ??
    ""
  );
}

function extractIncoming(body) {
  const msg = (body?.messages || []).find((m) => !m.from_me);
  if (!msg) return null;
  const from = msg.chat_id || msg.from || "";
  return from ? { from, text: extractText(msg) } : null;
}

async function sendText(to, body) {
  const res = await fetch(WHAPI.apiUrl + "/messages/text", {
    method: "POST",
    headers: { Authorization: "Bearer " + WHAPI.token, "Content-Type": "application/json" },
    body: JSON.stringify({ to, body }),
  });
  if (!res.ok) console.error("Whapi error", res.status, await res.text().catch(() => ""));
}

const app = express();
app.use(express.json());

app.post("/webhook", async (req, res) => {
  const incoming = extractIncoming(req.body);
  if (incoming) {
    const s = sessions[incoming.from] || (sessions[incoming.from] = { state: null, vars: {} });
    for (const reply of await handleMessage(FLOW, incoming.text, s)) await sendText(incoming.from, reply);
  }
  res.sendStatus(200);
});

app.get("/", (_req, res) => res.send("${title(flow, " (Whapi.cloud)")} is running. Webhook: /webhook"));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log("Bot listening on :" + PORT + " — webhook: /webhook"));
`;
}

function generateStandalone(flow) {
  if (flow.provider === "meta") return generateMeta(flow);
  if (flow.provider === "green") return generateGreen(flow);
  if (flow.provider === "whapi") return generateWhapi(flow);
  return generateTwilio(flow);
}

/* ---------- full-project export (for the ZIP download) ---------- */

const PROVIDER_INFO = {
  twilio: {
    label: "Twilio WhatsApp",
    webhook: "POST /whatsapp",
    env: ["TWILIO_SID=your_account_sid", "TWILIO_TOKEN=your_auth_token"],
    steps: [
      "Create a Twilio account and open the WhatsApp Sandbox (Messaging → Try it out).",
      "Deploy this server (or expose it locally with `npx ngrok http 3000`).",
      "In the Sandbox settings, set “When a message comes in” to `https://<your-host>/whatsapp`.",
      "Join the sandbox from your phone and message the sandbox number.",
    ],
  },
  meta: {
    label: "Meta WhatsApp Cloud API",
    webhook: "GET+POST /webhook",
    env: ["META_ACCESS_TOKEN=your_access_token", "META_PHONE_NUMBER_ID=your_phone_number_id", "META_VERIFY_TOKEN=your_verify_token"],
    steps: [
      "Create a Meta developer app with the WhatsApp product (free test number included).",
      "Deploy this server (or expose it locally with `npx ngrok http 3000`).",
      "In WhatsApp → Configuration, set the webhook URL to `https://<your-host>/webhook` with your verify token, and subscribe to `messages`.",
      "Send a message to your test number from an allowed recipient.",
    ],
  },
  green: {
    label: "Green API",
    webhook: "POST /webhook",
    env: ["GREEN_ID_INSTANCE=your_instance_id", "GREEN_API_TOKEN_INSTANCE=your_api_token"],
    steps: [
      "Create an instance at green-api.com and pair your WhatsApp by scanning the QR code.",
      "Deploy this server (or expose it locally with `npx ngrok http 3000`).",
      "In the instance settings, set the incoming webhook URL to `https://<your-host>/webhook`.",
      "Message the paired WhatsApp number from any phone.",
    ],
  },
  whapi: {
    label: "Whapi.cloud",
    webhook: "POST /webhook",
    env: ["WHAPI_TOKEN=your_channel_token"],
    steps: [
      "Create a channel at whapi.cloud and pair your WhatsApp by scanning the QR code.",
      "Deploy this server (or expose it locally with `npx ngrok http 3000`).",
      "In the channel settings, set the webhook URL to `https://<your-host>/webhook` for message events.",
      "Message the paired WhatsApp number from any phone.",
    ],
  },
};

function generateReadme(flow, info) {
  const name = flow.name || "FlowBot";
  return `# ${name}

Standalone WhatsApp bot generated by FlowBot from your flowchart.
Deterministic runtime — no AI, no external services beyond your WhatsApp provider (${info.label}).

## Quick start

\`\`\`bash
npm install
cp .env.example .env   # fill in your ${info.label} credentials
npm run start:env      # bot listens on :3000 — webhook: ${info.webhook}
\`\`\`

(Credentials you entered in FlowBot are also baked into \`server.js\` as fallbacks,
so plain \`npm start\` works too.)

## Connect it to WhatsApp (${info.label})

${info.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Files

- \`server.js\` — the complete bot: your flow (as JSON), the FlowBot engine, and the ${info.label} webhook wiring.
- \`.env.example\` — credentials template. Copy to \`.env\`; \`npm start\` loads it automatically.
- \`package.json\` — one dependency (express).

## Editing the bot

The conversation lives in the \`FLOW\` object at the top of \`server.js\` — nodes are blocks,
edges are the wires between them. For bigger changes, edit the flow visually in FlowBot
and download a fresh ZIP.
`;
}

function generateProject(flow) {
  const provider = PROVIDER_INFO[flow.provider] ? flow.provider : "twilio";
  const info = PROVIDER_INFO[provider];
  const pkg = {
    name: (flow.name || "flowbot-bot").toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "flowbot-bot",
    version: "1.0.0",
    private: true,
    description: `WhatsApp bot generated by FlowBot (${info.label})`,
    main: "server.js",
    scripts: { start: "node server.js", "start:env": "node --env-file=.env server.js" },
    engines: { node: ">=20" },
    dependencies: { express: "^4.21.2" },
  };
  return [
    { name: "server.js", data: generateStandalone(flow) },
    { name: "package.json", data: JSON.stringify(pkg, null, 2) + "\n" },
    { name: "README.md", data: generateReadme(flow, info) },
    { name: ".env.example", data: info.env.join("\n") + "\n" },
  ];
}

module.exports = { generateStandalone, generateProject };
